Repository matthewfeickert/pythia-python, pull requests merged in 2020-04, with the labels that each got.

#9 refactor: Use ENTRYPOINT and CMD to improve command line interface
  .github/workflows/ci.yml
  Dockerfile
  Makefile
  README.md
Labels: refactor, tests

#10 refactor: Use better COPY practices to reduce image size
  Dockerfile
Labels: refactor

#8 feat: Add HepMC
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  Dockerfile
  Makefile
  README.md
  tests/main42.cc
  tests/main42.cmnd
Labels: enhancement, good first issue
